apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-storage-limits
  namespace: dev-team
spec:
  limits:
  - type: PersistentVolumeClaim
    min:
      storage: 1Gi
    max:
      storage: 100Gi
    default:
      storage: 10Gi
    defaultRequest:
      storage: 5Gi
