apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-storage-limits
  namespace: dev-team
spec:
  limits:
  - type: PersistentVolumeClaim
    min: #minimum allowed for each container
      storage: 1Gi
    max: #maximum allowed for each container
      storage: 100Gi
    default: #default limits if not specified in container spec
      storage: 10Gi
    defaultRequest: #default resource requests
      storage: 5Gi
