apiVersion: v1
kind: ResourceQuota
metadata:
  name: limit-compute
  namespace: my-namespace
spec:
  hard:
    # These look a little odd because they're not nested but they refer to the requests and limit fields in a Pod
    requests.cpu: "16"        # Total CPU requested across all pods <= 16 cores
    requests.memory: 100Gi    # Total memory requested across all pods <= 100Gi
    limits.cpu: "16"          # Total CPU limits across all pods <= 16 cores
    limits.memory: 100Gi      # Total memory limits across all pods <= 100Gi
