apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  template:
    spec:
      containers:
      - name: example
        image: busybox
        command: ["echo", "Hello from the Kubernetes Job!"]
      restartPolicy: Never
  backoffLimit: 4
