apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limit-range
  namespace: dev-team
spec:
  limits:
  - type: Pod
    max: #total maximum resources across all containers in a pod
      cpu: "2"
      memory: 2Gi
    min: #total minimum resources across all containers in a pod
      cpu: "0.2"
      memory: 256Mi
