apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple-cron
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-cron
            image: busybox
            command: ["echo", "Hello from Kubernetes CronJob!"]
          restartPolicy: OnFailure
